### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by BoHoehne** [gift-surg/ITK_NiftyMIC#1]
Hello,

### Description

i am unable to compile the Project. The compiler is complaining missing files.

 ### Steps to Reproduce

Compile the Project with x64 Linux and GCC

### Expected behavior

Compiled code

### Actual behavior

Compile breaks with file not found error

### Reproducibility

Happens at about 55 - 65% of Compile

### Environment

Linux 5.01 (x86_64) and GCC 8.3.1

**Comment by renbem** [comment]
Hi BeeHoh,
As ITK_NiftyMIC builds on (standard) ITK 4.13.1 please make sure that you meet the associated requirements. I compiled it using gcc 5.4 on Ubuntu 16.04 which ran smoothly. Hope that helps.
Best,
Michael

**Comment by BoHoehne** [comment]
As I am not able to switch to Ubuntu or outdatet GCC versions I tried with the tool set i mentioned above. Also, I tried to follow the documentation as closely as possible.
Here is the outcome of my latest compile run:
--------------------------------------------------
..
[ 59%] Generating itkImageToImageFilterBPython.cpp, ../../../lib/itkImageToImageFilterBPython.py
Fatal error: glibc detected an invalid stdio handle
make[2]: *** [Wrapping/Modules/ITKFiniteDifference/CMakeFiles/ITKFiniteDifferencePython.dir/build.make:307: Wrapping/Modules/ITKFiniteDifference/itkFiniteDifferenceImageFilterPython.cpp] Aborted (core dumped)
make[1]: *** [CMakeFiles/Makefile2:15721: Wrapping/Modules/ITKFiniteDifference/CMakeFiles/ITKFiniteDifferencePython.dir/all] Error 2
[ 59%] Generating itkInPlaceImageFilterAPython.cpp, ../../../lib/itkInPlaceImageFilterAPython.py
[ 59%] Generating itkScalarImageToTextureFeaturesFilterPython.cpp, ../../../lib/itkScalarImageToTextureFeaturesFilterPython.py
make[2]: *** [Wrapping/Modules/ITKCurvatureFlow/CMakeFiles/ITKCurvatureFlowPython.dir/build.make:107: Wrapping/Modules/ITKCurvatureFlow/itkMinMaxCurvatureFlowImageFilterPython.cpp] Segmentation fault (core dumped)
make[1]: *** [CMakeFiles/Makefile2:16103: Wrapping/Modules/ITKCurvatureFlow/CMakeFiles/ITKCurvatureFlowPython.dir/all] Error 2
[ 59%] Generating itkInPlaceImageFilterBPython.cpp, ../../../lib/itkInPlaceImageFilterBPython.py
[ 59%] Generating itkRigid3DTransformPython.cpp, ../../../lib/itkRigid3DTransformPython.py
make[2]: *** [Wrapping/Modules/ITKCommon/CMakeFiles/ITKCommonPython.dir/build.make:685: Wrapping/Modules/ITKCommon/itkInPlaceImageFilterAPython.cpp] Segmentation fault (core dumped)
make[2]: *** Waiting for unfinished jobs....

VolumeSplineKernelTransformPython.cpp.o
[ 59%] Linking CXX shared module ../../../lib/_ITKTransformPython.so
[ 60%] Built target ITKTransformPython
[ 60%] Linking CXX shared module ../../../lib/_ITKStatisticsPython.so
[ 60%] Built target ITKStatisticsPython
make[1]: *** [CMakeFiles/Makefile2:15277: Wrapping/Modules/ITKCommon/CMakeFiles/ITKCommonPython.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

--------------------------------------------------
I also tried the provided VirtualBox Image. It is, in essence, disfunctional.
It only boots into rescue mode.

Have you ever thought about a docker image ? 
Docker also provides Alpine Linux which is very light weight.

Regards

**Comment by renbem** [comment]
Dear BeeHoh,

Re ITK_NiftyMIC compilation: As I am sure you will understand, I cannot provide remote support for the, as mentioned in-essence, standard ITK 4.13.1 compilation. I can assure that it compiles also with more recent GCC versions. The virtual machine, for example, is based on Ubuntu 18.04 and uses GCC 7.3.0. If this problem persists on your platform, please reach out the ITK-specific forums for support.

Re the virtual machine: The provided virtual machine is up and running at various platforms and users of various institutions. What you experience is most likely associated with point 3 here: https://github.com/gift-surg/NiftyMIC/wiki/niftymic-virtualbox#virtualbox-set-up 
Please follow the provided instructions and I am happy to assist if needed.

Best wishes,
Michael

**Comment by renbem** [comment]
Update: Docker images are now available as well; see [ITK_NiftyMIC](https://hub.docker.com/r/renbem/itk_niftymic) and [NiftyMIC](https://hub.docker.com/r/renbem/niftymic)
